stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    outs:
    - data/processed/divorce.csv
  data_separation:
    cmd: python src/stages/separate_data.py --config=params.yaml
    deps:
    - src/stages/separate_data.py
  split_data:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - src/stages/data_split.py
    outs:
    - data/processed/x_train.csv
    - data/processed/x_test.csv
    - data/processed/y_train.csv
    - data/processed/y_test.csv
    - data/processed/x_val.csv
    - data/processed/y_val.csv
  scale_data:
    cmd: python src/stages/scale_data.py --config=params.yaml
    deps:
    - src/stages/scale_data.py
    - data/processed/x_train.csv
    - data/processed/x_test.csv
    - data/processed/x_val.csv
    outs:
    - data/processed/x_df_training_scaled.csv
    - data/processed/X_df_validation_scaled.csv
    - data/processed/x_df_test_scaled.csv
  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - src/stages/train.py
    - data/processed/x_df_training_scaled.csv
    - data/processed/X_df_validation_scaled.csv
    - data/processed/x_df_test_scaled.csv
    outs:
    - models/model_grid_search_logReg.joblib
    - models/logReg.joblib
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - src/stages/evaluate.py
    - models/model_grid_search_logReg.joblib
    - models/logReg.joblib
    outs:
    - reports/matrix_conf.png
